site_name: ThreatCompute Documentation
site_description: Automated Threat Modeling & Attack Graph Framework for Kubernetes
site_url: https://threatcompute.github.io/ThreatCompute/
repo_name: ThreatCompute/ThreatCompute
repo_url: https://github.com/ThreatCompute/ThreatCompute
nav:
  - Home: index.md
  - Getting Started:
      - Installation: installation.md
      - Offline Mode: development/offline_mode.md
  - Usage:
      - Threat Modeling Pipeline: usage/threat_modeling.md
      - Attack Graph Generation: usage/attack_graph.md
      - Time To Compromise (TTC): usage/ttc.md
  - Development:
      - Contributing: development/contributing.md
  - API Overview: api/overview.md
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: blue
      accent: indigo
  logo: images/logo.png
  favicon: images/logo.png
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - tables
  - attr_list
  - def_list
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.critic
  - pymdownx.tasklist:
      custom_checkbox: true
extra:
  offline_mode_env: TC_OFFLINE
plugins:
  - search
  - tags
  - git-revision-date-localized:
      fallback_to_build_date: true
