K8S_MATRIX = {
    "Collection": ["Collecting data from pod", "Images from a private registry"],
    "Defense Evasion": [
        "Clear container logs",
        "Delete Kubernetes events",
        "Pod or container name similarity",
        "Connect from proxy server",
    ],
    "Initial Access": [
        "Exposed sensitive interfaces",
        "Kubeconfig file",
        "Compromised image In registry",
        "Using cloud credentials",
        "Application vulnerability",
    ],
    "Discovery": [
        "Access Kubernetes API server",
        "Access Kubelet API",
        "Network mapping",
        "Instance Metadata API",
        "Exposed sensitive interfaces",
    ],
    "Privilege Escalation": [
        "Access cloud resources",
        "Cluster-admin binding",
        "Privileged container",
        "hostPath mount",
    ],
    "Execution": [
        "Bash or cmd inside container",
        "Sidecar injection",
        "SSH server running inside container",
        "New container",
        "Application exploit (RCE)",
        "Exec into container",
    ],
    "Persistence": [
        "Kubernetes CronJob",
        "Writable hostPath mount",
        "Static pods",
        "Malicious admission controller",
        "Backdoor container",
        "Container service account",
    ],
    "Lateral Movement": [
        "Access cloud resources",
        "Container service account",
        "ARP poisoning and IP spoofing",
        "CoreDNS poisoning",
        "Cluster internal networking",
        "Application credentials in configuration files",
        "Writable hostPath mount",
    ],
    "Credential Access": [
        "Application credentials in configuration files",
        "Access Managed Identity credentials",
        "Mount service principal",
        "List Kubernetes secrets",
        "Container service account",
        "Malicious admission controller",
    ],
    "Impact": ["Data destruction", "Denial of service", "Resource hijacking"],
}
