name: CI

on:
  push:
    branches: [ main, '**' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.10', '3.11', '3.12', '3.13' ]
    env:
      TC_OFFLINE: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov codecov
      - name: Run tests with coverage
        run: |
          source .venv/bin/activate
          export PYTHONPATH=.:$PYTHONPATH
          pytest --cov=ThreatModeling --cov=AttackGraphGeneration --cov=TTCComputation --cov-report=xml --cov-report=term-missing -q
      - name: Upload coverage to Codecov (single job)
        if: matrix.python-version == '3.13'
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          fail_ci_if_error: true
          flags: unittests
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  # Documentation deployment handled by docs.yaml workflow
